In [3]:
#create arrays
import numpy as np

In [6]:
a = np.array([1,4,8])
print(a)
print(a.dtype)

b = np.array([4.2,3.8,4.1])
print(b.dtype)

[1 4 8]
int64
float64


In [7]:
b = np.array([(1.2,3.4,1.9), (7,8,9)])
print(b)

[[1.2 3.4 1.9]
 [7.  8.  9. ]]


In [8]:
c = np.array([[1,2],[3,4]], dtype= complex)
print(c)

[[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]]


In [16]:
print(np.zeros((3,4)))
print(np.ones((2,2), dtype=np.int32))
#random
print(np.empty((3,2)))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1 1]
 [1 1]]
[[1.2 3.4]
 [1.9 7. ]
 [8.  9. ]]


In [18]:
print(np.arange(10,30,5))

[10 15 20 25]


In [20]:
print(np.arange(1.1,2,0.1))

[1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8 1.9]


In [21]:
#using linespace instead of arange
print(np.linspace(0,2,9))

[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]


In [24]:
temp = np.arange(12).reshape(4,3)
print(temp)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [25]:
print(np.arange(24).reshape(2,3,4))

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [26]:
temp = np.array([10,20,30,40])
print(temp<25)

[ True  True False False]


In [28]:
#matrix product
A = np.array([[1,1],[0,1]])
B = np.array([[2,0],[0,4]])
print(A@B)
print('dot fn')
print(A.dot(B))

[[2 4]
 [0 4]]
dot fn
[[2 4]
 [0 4]]


In [29]:
#random number generator
rg = np.random.default_rng(1)
b = rg.random((2,3))
print(b)

[[0.51182162 0.9504637  0.14415961]
 [0.94864945 0.31183145 0.42332645]]


In [37]:
a = rg.random((2,3))
print(a)
print(f'The sum is {a.sum()}')
print(f'The min is {a.min()}')
print(f'The max is {a.max()}')

[[0.45933588 0.06234958 0.64132817]
 [0.85263284 0.59294102 0.26009745]]
The sum is 2.8686849354968182
The min is 0.0623495791498756
The max is 0.8526328384806567
