In [1]:
import csv
with open('/home/AIML_Student/Documents/210962022_ML/week1/ex.csv','rt') as f:
    data = csv.reader(f)
    for row in data:
        print(row)

['Title1', ' Title2', ' Title3']
['one', 'two', 'three']
['ex1', 'ex2', 'ex3']


In [2]:
#dictionary
import csv
reader = csv.DictReader(open('/home/AIML_Student/Documents/210962022_ML/week1/weekdays.csv','rt'))
for raw in reader:
    print(raw)

{'Sunday': 'Thursday', 'Monday': 'Friday', 'Tuesday': 'Saturday', 'Wednesday': ''}


In [3]:
#writing in csv
import csv
with open("/home/AIML_Student/Documents/210962022_ML/week1/data1.csv", mode="w") as file:
    writer = csv.writer(file,delimiter=',', quotechar='"',quoting=csv.QUOTE_MINIMAL)
    writer.writerow(['Programming Language', 'Designed by', 'Appeared', 'Extension'])
    writer.writerow(['Python','Guido Van Rossam', '1991', '.py'])
    writer.writerow(['Java', 'James Gosling', '1995', '.java'])
    writer.writerow(['C++', 'Bjarne', '1985','.cpp'])

In [4]:
#using pandas
import pandas as pd
result = pd.read_csv('/home/AIML_Student/Documents/210962022_ML/week1/data1.csv')
print(result)

  Programming Language       Designed by  Appeared Extension
0               Python  Guido Van Rossam      1991       .py
1                 Java     James Gosling      1995     .java
2                  C++            Bjarne      1985      .cpp


In [5]:
#writing using pandas
from pandas import DataFrame
temp = {'Sem3':['DS','OOP','IDAP'],
       'Credits':['4','3','3'],
       'Grade':['A','A','B'],
       }
df = DataFrame(temp,columns=['Sem3','Credits','Grade'])
export_csv = df.to_csv(r'/home/AIML_Student/Documents/210962022_ML/week1/data2.csv', index=None, header=True)
print(df)

   Sem3 Credits Grade
0    DS       4     A
1   OOP       3     A
2  IDAP       3     B


In [6]:
#create arrays
import numpy as np

In [7]:
a = np.array([1,4,8])
print(a)
print(a.dtype)

b = np.array([4.2,3.8,4.1])
print(b.dtype)

[1 4 8]
int64
float64


In [8]:
b = np.array([(1.2,3.4,1.9), (7,8,9)])
print(b)

[[1.2 3.4 1.9]
 [7.  8.  9. ]]


In [9]:
c = np.array([[1,2],[3,4]], dtype= complex)
print(c)

[[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]]


In [10]:
print(np.zeros((3,4)))
print(np.ones((2,2), dtype=np.int32))
#random
print(np.empty((3,2)))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1 1]
 [1 1]]
[[1.2 3.4]
 [1.9 7. ]
 [8.  9. ]]


In [11]:
print(np.arange(10,30,5))

[10 15 20 25]


In [12]:
print(np.arange(1.1,2,0.1))

[1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8 1.9]


In [13]:
#using linespace instead of arange
print(np.linspace(0,2,9))

[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]


In [14]:
temp = np.arange(12).reshape(4,3)
print(temp)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [15]:
print(np.arange(24).reshape(2,3,4))

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [16]:
temp = np.array([10,20,30,40])
print(temp<25)

[ True  True False False]


In [17]:
#matrix product
A = np.array([[1,1],[0,1]])
B = np.array([[2,0],[0,4]])
print(A@B)
print('dot fn')
print(A.dot(B))

[[2 4]
 [0 4]]
dot fn
[[2 4]
 [0 4]]


In [18]:
#random number generator
rg = np.random.default_rng(1)
b = rg.random((2,3))
print(b)

[[0.51182162 0.9504637  0.14415961]
 [0.94864945 0.31183145 0.42332645]]


In [19]:
a = rg.random((2,3))
print(a)
print(f'The sum is {a.sum()}')
print(f'The min is {a.min()}')
print(f'The max is {a.max()}')

[[0.82770259 0.40919914 0.54959369]
 [0.02755911 0.75351311 0.53814331]]
The sum is 3.1057109529998157
The min is 0.027559113243068367
The max is 0.8277025938204418


In [20]:
# convert 1D array to 2D array
import numpy as np
a = np.array([0,1,2,3,4,5,6,7,8])
print(a.reshape(3,3))

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [21]:
# replace all odd numbers with -1
import numpy as np
a = np.array([0,1,2,3,4,5,6,7,8])
a[a%2==1] = -1
print(a)

[ 0 -1  2 -1  4 -1  6 -1  8]


In [22]:
#positions with greater value
import numpy as np
x = np.array([21, 64, 86, 22, 74, 55, 81, 79, 90, 89])
y = np.array([21, 7, 3, 45, 10, 29, 55, 4, 37, 18])

print(np.where(x>y))
print(np.where(x==y))

(array([1, 2, 4, 5, 6, 7, 8, 9]),)
(array([0]),)


In [23]:
import numpy as np
temp = np.arange(100).reshape(5,-1)
# print(temp)
print(temp[0:5,0:4])

[[ 0  1  2  3]
 [20 21 22 23]
 [40 41 42 43]
 [60 61 62 63]
 [80 81 82 83]]
