In [2]:
# convert 1D array to 2D array
import numpy as np
a = np.array([0,1,2,3,4,5,6,7,8])
print(a.reshape(3,3))

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [3]:
# replace all odd numbers with -1
import numpy as np
a = np.array([0,1,2,3,4,5,6,7,8])
a[a%2==1] = -1
print(a)

[ 0 -1  2 -1  4 -1  6 -1  8]


In [6]:
#positions with greater value
import numpy as np
x = np.array([21, 64, 86, 22, 74, 55, 81, 79, 90, 89])
y = np.array([21, 7, 3, 45, 10, 29, 55, 4, 37, 18])

print(np.where(x>y))
print(np.where(x==y))

(array([1, 2, 4, 5, 6, 7, 8, 9]),)
(array([0]),)


In [11]:
import numpy as np
temp = np.arange(100).reshape(5,-1)
# print(temp)
print(temp[0:5,0:4])

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]]
[[ 0  1  2  3]
 [20 21 22 23]
 [40 41 42 43]
 [60 61 62 63]
 [80 81 82 83]]
